// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TourService.Data;

#nullable disable

namespace TourService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531000001_AddTourExecution")]
    partial class AddTourExecution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TourService.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId").HasColumnType("integer");
                    b.Property<string>("AuthorUsername").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").IsRequired().HasMaxLength(4000).HasColumnType("character varying(4000)");
                    b.Property<string>("Difficulty").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<decimal>("Price").HasColumnType("numeric");
                    b.Property<double>("LengthKm").HasColumnType("double precision");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<string[]>("Tags").IsRequired().HasColumnType("text[]");
                    b.Property<DateTime?>("PublishedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("ArchivedAtUtc").HasColumnType("timestamp with time zone");

                    b.HasKey("Id");
                    b.HasIndex("AuthorId");
                    b.ToTable("Tours");
                });

            modelBuilder.Entity("TourService.Models.TourExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TourId").HasColumnType("integer");
                    b.Property<int>("TouristId").HasColumnType("integer");
                    b.Property<string>("Status").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<DateTime>("StartedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("CompletedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("AbandonedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("LastActivityAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<double>("InitialLatitude").HasColumnType("double precision");
                    b.Property<double>("InitialLongitude").HasColumnType("double precision");

                    b.HasKey("Id");
                    b.HasIndex("TouristId");
                    b.HasIndex("TourId");
                    b.ToTable("TourExecutions");
                });

            modelBuilder.Entity("TourService.Models.CompletedKeyPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TourExecutionId").HasColumnType("integer");
                    b.Property<int>("KeyPointId").HasColumnType("integer");
                    b.Property<DateTime>("CompletedAtUtc").HasColumnType("timestamp with time zone");

                    b.HasKey("Id");
                    b.HasIndex("TourExecutionId");
                    b.HasIndex(new[] { "TourExecutionId", "KeyPointId" }).IsUnique();
                    b.ToTable("CompletedKeyPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
